base_url = "https://programmershideaway.xyz"

title = "Programmer's Hideaway"
description = "My Personal Website"

compile_sass = true
minify_html = true
highlight_code = true

build_search_index = true
generate_feed = true

default_language = "en"

theme = "mytheme"

taxonomies = [{ name = "tags", feed = true }]

[extra]

[extra.social]
mail = "ayushdevel@gmail.com"
github = "Ayush1325"
linkedin = "ayush-singh-665739204"
twitter = "AyushS1325"
mastodon = "@ayush1325"

[extra.support]
github = "Ayush1325"
liberapay = "Ayush1325"