base_url = "https://programmershideaway.xyz"

compile_sass = true
minify_html = true
highlight_code = true

build_search_index = true
generate_feed = true

default_language = "en"

theme = "DeepThought"

taxonomies = [
  { name = "tags", feed = true, paginate_by = 10},
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
smart_punctuation = true

[extra]
navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts" },
  { url = "$BASE_URL/tags", name = "Tags" },
 ]},
]

[extra.social]
email = "ayushdevel@gmail.com"
github = "Ayush1325"
linkedin = "ayush-singh-665739204"
kde = "oreki"

[extra.author]
name = "Ayush Singh"
avatar = "/images/avatar.jpg"
