base_url = "https://programmershideaway.xyz"

title = "Programmer's Hideaway"
description = "My Personal Website"

compile_sass = true
minify_html = true
highlight_code = true

build_search_index = true
generate_feed = true

default_language = "en"

theme = "mytheme"

taxonomies = [{ name = "tags", feed = true }]

[extra]
